# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml
  example.com:
    site_hosts:
      - example.dev
    local_path: ../nafve # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin_email@example.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
